# Generated by Django 4.2.3 on 2023-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa econômica'), ('IT', 'Itaú'), ('Br', 'Bradesco'), ('C6', 'C6')], max_length=2),
        ),
    ]
